name: CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  build-linux-glibc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build and Tests
        run: |
          cc -o first first.c
          ./first -T

  build-linux-musl:
    runs-on: ubuntu-latest

    container:
      image: alpine:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          apk add --no-cache xz curl build-base zstd-static zlib-static

      - name: Build and Tests
        run: |
          cc -o first first.c
          ./first -T

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build and Tests
        run: |
          cc -o first first.c
          ./first -T

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build and Tests
        run: |
          cl first.c
          ./first.exe -T
